# Generated by Django 5.1.4 on 2024-12-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageUploader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadeddata',
            name='details',
        ),
        migrations.AddField(
            model_name='uploadeddata',
            name='farmerID',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='uploadeddata',
            name='farmerName',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='uploadeddata',
            name='timeOfPhoto',
            field=models.TextField(null=True),
        ),
    ]
